New design for phishing warning page
MetaMask/phishing-warning pull request #52
Opened 2023-01-27 12:14 UTC by aleksandar-mihajlovic

## Explanation
Added new design for phishing warning page according to [figma design](https://www.figma.com/file/MKJnCnI8Xi2EVcRCNAHwOu/Improve-Phishing-Warning-Page?node-id=2%3A9&t=P2jLXBxUvqxA3A7d-0).
 
* Fixes #16602

## Screenshots/Screencaps

### Before
<img width="1672" alt="Screenshot 2023-01-26 at 16 01 52" src="https://user-images.githubusercontent.com/120601632/215083146-75e1cc15-312a-4fd4-8c95-de560d2bdb04.png">

### After
<img width="1679" alt="Screenshot 2023-01-27 at 13 13 37" src="https://user-images.githubusercontent.com/120601632/215084540-b73f7bf0-b3cc-424e-9be8-0f80d59419b7.png">

## Manual Testing Steps

Production testing:
1. Go to one of the links: primalfrens.club, geishateahouse.io, cryptocity.fun
2. Phishing warning page is displayed
3. All links are working
4. When back to safety is clicked, tab is closed

Local testing:
1. static/ folder
2. Double click on index.html
3. Phishing warning page is displayed
4. All links are working expect continue to the site, because production app is needed for that
5. When back to safety is clicked, tab is closed

2023-01-27 23:33 UTC, georgewrmarshall requested changes
Hey @aleksandar-mihajlovic, nice work matching the Figma design but I think it breaks some of the MetaMask design system conventions that I think should be resolved before this get's merged.

Hey @holantonela, I've left some comments in the Figma file https://www.figma.com/file/MKJnCnI8Xi2EVcRCNAHwOu?node-id=4:49#355806441

2023-01-27 23:33 UTC, georgewrmarshall commented on static/index.css
> +  background-color: #d03242;
As a general rule a static hex value should be a red flag. We should be using the design token css color variables available

```suggestion
  background-color: var(--color-error-default);
```

2023-01-27 23:33 UTC, georgewrmarshall commented on static/index.css
> +  color: white;
Can we use design token CSS vars here?

```suggestion
  color: var(--color-error-inverse);
```

2023-01-27 23:33 UTC, georgewrmarshall commented on static/index.css
> +  background: white;
Use color tokens 
```suggestion
  background: var(--color-error-inverse);
```

2023-01-30 08:45 UTC, aleksandar-mihajlovic commented on static/index.css
> +  background-color: #d03242;
Yes, seen that little late, will fix it

2023-01-30 08:45 UTC, aleksandar-mihajlovic commented on static/index.css
> +  color: white;
Yes, seen that little late, will fix it

2023-01-30 08:45 UTC, aleksandar-mihajlovic commented on static/index.css
> +  background: white;
Yes, seen that little late, will fix it

2023-01-30 10:28 UTC, dzfjz commented
Verified by QA

2023-01-30 13:36 UTC, holantonela commented on static/index.css
> +  background-color: #d03242;
You should use the error default red color @aleksandar-mihajlovic

2023-01-30 13:37 UTC, holantonela commented
@georgewrmarshall commented in the figma. Someone introduced that change, but i bet it was a click error. Please, @aleksandar-mihajlovic lets remove the border and the shadow of the title. Thank you!

2023-01-30 14:09 UTC, aleksandar-mihajlovic commented on static/index.css
> +  background-color: #d03242;
It is fixed now

2023-01-30 17:12 UTC, georgewrmarshall reviewed
Looking good! Have made one more suggestion. Thanks for your patience @aleksandar-mihajlovic 🙏

2023-01-30 17:12 UTC, georgewrmarshall commented on static/index.css
> +  font-family: Euclid, Roboto, Helvetica, Arial, sans-serif;
@garrettbear can you please suggest the correct css for the button here?

You can add some of the typography tokens here in favour of the static typography styles @aleksandar-mihajlovic 

```scss
button {
  font-family: var(--typography-s-body-md-font-family);
  font-weight: var(--typography-s-body-md-font-weight);
  font-size: var(--typography-s-body-md-font-size);
  line-height: var(--typography-s-body-md-line-height);
  letter-spacing: var(--typography-s-body-md-letter-spacing);

  @media screen and (min-width: 768px) {
    font-family: var(--typography-l-body-md-font-family);
    font-weight: var(--typography-l-body-md-font-weight);
    font-size: var(--typography-l-body-md-font-size);
    line-height: var(--typography-l-body-md-line-height);
    letter-spacing: var(--typography-l-body-md-letter-spacing);
  }
}
```

2023-01-30 22:35 UTC, georgewrmarshall commented on static/index.css
> +  font-family: Euclid, Roboto, Helvetica, Arial, sans-serif;
You can update the typography style to use the design token CSS variables for the typography too.

```suggestion
  color: var(--color-error-alternative);
  background: var(--color-error-inverse);
  padding: 1em;
  border-radius: 2em;
  border: none;
  float: right;
  margin-top: 3em;
  font-family: var(--typography-s-body-md-font-family);
  font-weight: var(--typography-s-body-md-font-weight);
  font-size: var(--typography-s-body-md-font-size);
  line-height: var(--typography-s-body-md-line-height);
  letter-spacing: var(--typography-s-body-md-letter-spacing);

  @media screen and (min-width: 768px) {
    font-family: var(--typography-l-body-md-font-family);
    font-weight: var(--typography-l-body-md-font-weight);
    font-size: var(--typography-l-body-md-font-size);
    line-height: var(--typography-l-body-md-line-height);
    letter-spacing: var(--typography-l-body-md-letter-spacing);
  }
```

2023-01-31 18:57 UTC, holantonela commented on static/index.html
> +        <p>Advisory provided by Ethereum Phishing Detector, CryptoScamDB, and PhishFort.</p>
This list should be dynamic. We should expose ONLY the sources who are flagging the current URL @aleksandar-mihajlovic @dzfjz

2023-01-31 21:02 UTC, georgewrmarshall reviewed
Looking good. There maybe one more update needed to the button that is being resolved in the Figma file

2023-01-31 21:02 UTC, georgewrmarshall commented on static/index.html
> +    <link rel="stylesheet" href="https://raw.githubusercontent.com/MetaMask/design-tokens/main/src/css/design-tokens.css">
I don't think we want to include this line it was just to check if we could get the phishing page to render with the correct design token css variables. We do need a dev environment for this repo though.

2023-01-31 21:07 UTC, NicholasEllul commented on static/index.html
> +        document.getElementById("suspect-link").innerHTML = document.referrer;
Setting `.innerHTML` can have [security implications](https://dev.to/caffiendkitten/innerhtml-cross-site-scripting-agc).  In this case innerText should work as well 👍 

```suggestion
        document.getElementById("suspect-link").innerText = document.referrer;
```

2023-01-31 21:15 UTC, NicholasEllul reviewed
This page looks fantastic! Glad to see it being implemented

2023-01-31 21:15 UTC, NicholasEllul commented on static/index.html
> +        <button class="button btn--rounded btn-primary" type="submit" onclick="window.close()">Back to safety</button>
On mobile, clicking back to safety returns the user to the previous page. Do we want to do `history.back()` here?

2023-02-01 11:54 UTC, holantonela commented on static/index.html
> +        <button class="button btn--rounded btn-primary" type="submit" onclick="window.close()">Back to safety</button>
We agreed that closing the tab is safer and more reliable than going back. The behaviour should be the same in mobile and desktop. The discussion is here https://www.figma.com/file/MKJnCnI8Xi2EVcRCNAHwOu?node-id=4:49#266099480

2023-02-01 11:55 UTC, holantonela commented on static/index.html
> +        <p>Advisory provided by Ethereum Phishing Detector, CryptoScamDB, and PhishFort.</p>
To do so, we need to add a query string in the `PhishingController` to say which list flagged it. cc @409H

2023-02-01 15:53 UTC, holantonela commented on static/index.html
> +        <p>Advisory provided by Ethereum Phishing Detector, CryptoScamDB, and PhishFort.</p>
This is the point 2 in the **Acceptance Criteria** 

> 2. Users can read the attribution to who flagged the domain, probably passed to that page with a query string.

https://github.com/MetaMask/metamask-extension/issues/16602

2023-02-03 10:21 UTC, aleksandar-mihajlovic commented on static/index.css
> +  font-family: Euclid, Roboto, Helvetica, Arial, sans-serif;
Updated that now

2023-02-03 10:21 UTC, aleksandar-mihajlovic commented on static/index.html
> +        <p>Advisory provided by Ethereum Phishing Detector, CryptoScamDB, and PhishFort.</p>
Well, as I understand, these websites are not scam websites, they are websites that give users info about how to avoid phishing, so they don't need to be listed dynamically. Am I wrong?
And about source that is scam website, the link will be shown in this sentence:
`Potential threats on {someWebsite} include:`
but i cannot demo it, because i cannot build the project and connect with extension to test it out, but website link will be there once it goes to production.
@holantonela

2023-02-03 10:21 UTC, aleksandar-mihajlovic commented on static/index.html
> +        document.getElementById("suspect-link").innerHTML = document.referrer;
I will fix that

2023-02-03 10:21 UTC, aleksandar-mihajlovic commented on static/index.html
> +    <link rel="stylesheet" href="https://raw.githubusercontent.com/MetaMask/design-tokens/main/src/css/design-tokens.css">
I will fix that

2023-02-03 10:21 UTC, aleksandar-mihajlovic commented on static/index.html
> +        <button class="button btn--rounded btn-primary" type="submit" onclick="window.close()">Back to safety</button>
Won't history.back(), return to previous page or am i wrong?

2023-02-03 10:21 UTC, aleksandar-mihajlovic commented on static/index.html
> +        <button class="button btn--rounded btn-primary" type="submit" onclick="window.close()">Back to safety</button>
@NicholasEllul and just to add, this ticket is related to the extension, not for mobile app

2023-02-03 10:21 UTC, aleksandar-mihajlovic commented on static/index.html
> +        <p>Advisory provided by Ethereum Phishing Detector, CryptoScamDB, and PhishFort.</p>
I am not sure that I understand what I need to do here, because i am not sure what i am doing wrong, if you could explain it to me

2023-02-03 13:02 UTC, aleksandar-mihajlovic commented
@georgewrmarshall can you check the attached gif, is the button okay now? I used the Button Secondary as mentioned in Figma.

2023-02-03 13:05 UTC, Gudahtt commented on static/index.html
> +        <p>Advisory provided by Ethereum Phishing Detector, CryptoScamDB, and PhishFort.</p>
Thanks @holantonela , great catch

>Well, as I understand, these websites are not scam websites, they are websites that give users info about how to avoid phishing, so they don't need to be listed dynamically. Am I wrong?

I can explain the purpose of this a criteria a little more. The concern is that we want the user to know _specifically_ why the site is blocked, so that they can know who to file an issue with if they believe it was flagged in error. For example, we don't want users making issues on our phishing detect repo for sites that are blocked by Phishfort, because we can't do anything about that. They would need to go to Phishfort.

To that end, we'll want to update the "report a problem" link to be dynamic as well, so it points the user in the right direction.

2023-02-03 14:16 UTC, aleksandar-mihajlovic commented on static/index.html
> +        <p>Advisory provided by Ethereum Phishing Detector, CryptoScamDB, and PhishFort.</p>
Okay, thank you for this clarification, this is was very helpful. I will investigate and fix this. Just one question, are there more detect repo's besides Metamask and Phishfort? @Gudahtt

2023-02-06 03:53 UTC, georgewrmarshall reviewed
Looking good! I've created another PR with some more CSS suggestions https://github.com/MetaMask/phishing-warning/pull/55 that you can review and merge into this PR if you think they are acceptable.

2023-02-06 12:31 UTC, aleksandar-mihajlovic commented
I have added the CSS code that you suggested @georgewrmarshall if you can check it out.
I have added logic for setting dynamically text and link also, for phishing detection repo that detected phishing website, if you can check it out @holantonela.

2023-02-06 16:19 UTC, weizman requested changes
minor security concern

2023-02-06 16:19 UTC, weizman commented on static/index.html
> +          MetaMask flagged the site you're trying to visit as potentially deceptive. Attackers may trick you into doing something dangerous. <a id="csdbLink" href='' onclick="window.open('https://cry
this call unsafely allows reverse tab nabbing attacks (read more [here](https://github.com/orgs/MetaMask/projects/39/views/1?filterQuery=nabb&pane=issue&itemId=16010904)) - please fix by adding attribute `rel="noopener"`

2023-02-06 16:26 UTC, Gudahtt commented on static/index.html
> +        <p>Advisory provided by Ethereum Phishing Detector, CryptoScamDB, and PhishFort.</p>
Nope, we only support those two at the moment

2023-02-06 16:26 UTC, 409H commented on static/index.html
> +        <p>Advisory provided by Ethereum Phishing Detector, CryptoScamDB, and PhishFort.</p>
@aleksandar-mihajlovic only those two right now, but the logic allows us to add more. I think we can make the change in https://github.com/MetaMask/core/blob/main/packages/phishing-controller/src/PhishingController.ts#L58 to add the attribution for which list flagged it, and add that to the redirection query string for this phishing-warning to consume

2023-02-06 17:36 UTC, weizman commented on static/index.html
> +          MetaMask flagged the site you're trying to visit as potentially deceptive. Attackers may trick you into doing something dangerous. <a id="csdbLink" href='' onclick="window.open('https://cry
also, why use `onclick` and `open` when you have the default behaviour of an anchor element?

`<a id="csdbLink" rel="noopener" href='https://cryptoscamdb.org/search' target='_blank'">Learn more</a>`

2023-02-06 18:44 UTC, aleksandar-mihajlovic commented on static/index.html
> +          MetaMask flagged the site you're trying to visit as potentially deceptive. Attackers may trick you into doing something dangerous. <a id="csdbLink" href='' onclick="window.open('https://cry
Okay no problem, if it is making security problems, i will changed it right now, you can look at it, if it is okay. @weizman

2023-02-06 18:47 UTC, aleksandar-mihajlovic commented on static/index.html
> +        <p>Advisory provided by Ethereum Phishing Detector, CryptoScamDB, and PhishFort.</p>
@409H  I currently implemented logic to detect through current query string, I would say that I found a decent solution for now, but in future when other detect repo's are added, this logic should be updated too, if that is okay?

2023-02-06 19:51 UTC, AlexHerman1 commented
can we make sure that whatever ends up going to prod, we make the attribution prominent and point them towards the correct contributor to raise an issue?

2023-02-06 22:52 UTC, georgewrmarshall submitted a review, later dismissed
Looks great! Going to approve for visual and design system requirements. Nice work! 💯  Please don't merge until all reviewers have approved 🙏

2023-02-06 22:55 UTC, Gudahtt commented on static/index.html
> +        <p>Advisory provided by Ethereum Phishing Detector, CryptoScamDB, and PhishFort.</p>
@409H thanks for linking that, I had failed to consider this requirement when reviewing a cost-saving change to how we poll for the phishing list. Unfortunately this information will no longer be available after that change because we're now combining all lists into one to save on network bandwidth.

Still, we can fulfill this requirement without that data by checking on-demand after a user chooses to dispute a block. Tomorrow I will create a separate issue detailing how this needs to change.

2023-02-06 22:58 UTC, Gudahtt commented on static/index.html
> +        <p>Advisory provided by Ethereum Phishing Detector, CryptoScamDB, and PhishFort.</p>
@aleksandar-mihajlovic My apologies, I hadn't looked closely at this PR when I left my first comment.

I don't think we need the onload function you added for this, because that same logic is already handled by `index.ts`. It was implemented here: #23. We pass in a custom dispute URL if a site is blocked by Phishfort, otherwise we default to ours. As long as that `newIssueUrl` continues to be set dynamically on this link, no change to this behavior is needed here.

2023-02-07 11:30 UTC, aleksandar-mihajlovic commented on static/index.html
> +        <p>Advisory provided by Ethereum Phishing Detector, CryptoScamDB, and PhishFort.</p>
@Gudahtt Okay, i removed that part of the code for linking on the onload function, and returned to the old state like you mentioned, is it okay now?

2023-02-08 17:39 UTC, holantonela commented
> can we make sure that whatever ends up going to prod, we make the attribution prominent and point them towards the correct contributor to raise an issue?

Yes @AlexHerman1, we discussed it [here](https://github.com/MetaMask/phishing-warning/pull/52#pullrequestreview-1277832723)

2023-02-14 21:48 UTC, Gudahtt commented on src/index.test.ts
> -  it('should have correct default "New issue" link', () => {
It seems that this test should still work - was there a reason this was removed? It would be ideal to preserve it.

2023-02-14 21:48 UTC, Gudahtt commented on src/index.ts
> -  if (isValidSuspectHref(suspectHref) === false) {
Curious why this was removed. This was to prevent redirecting to unsupported protocols. We'll need to continue protecting against this at least as long as we're passing the blocked URL as a query parameter (i.e. so long as it's untrusted input).

2023-02-14 21:50 UTC, Gudahtt commented on static/index.html
> +        <p>Advisory provided by Ethereum Phishing Detector, CryptoScamDB, and PhishFort.</p>
Thanks @aleksandar-mihajlovic , yes this thread looks resolved now

2023-02-14 21:52 UTC, Gudahtt commented on static/index.html
> +        document.getElementById("suspect-link").innerText = document.referrer;
Nit: Could you move this code to the `start` function in `src/index.ts`? That is where all of our other "page initialization" code is.

2023-02-15 20:32 UTC, Gudahtt commented on src/index.ts
> -  if (isValidSuspectHref(suspectHref) === false) {
Oh I see. The affected component was removed in this redesign.

This is not critical then. This is a bizarre edge cases that would only be countered by users redirected to this page by a phisher.

2023-02-15 20:36 UTC, Gudahtt approved these changes
LGTM! I can address the remaining two nits in a follow-up PR.

2023-02-15 20:41 UTC, merged

2023-02-22 19:47 UTC, Gudahtt commented on src/index.test.ts
> -  it('should have correct default "New issue" link', () => {
Restored here: https://github.com/MetaMask/phishing-warning/pull/60