fix(18194): fix trigger to close window when clicking "back to safety"
MetaMask/phishing-warning pull request #84
Opened 2023-03-20 19:21 UTC by DDDDDanica

Fixes: https://app.zenhub.com/workspaces/extension-client-team-63529dce65cbb100265a3842/issues/gh/metamask/metamask-extension/18194

**After:** 

https://user-images.githubusercontent.com/12678455/226444138-501abd46-98a6-49f7-b625-f424423ae8fe.mov

2023-03-21 19:15 UTC, Gudahtt commented
Huh, interesting solution! It seems that this is an attempt to circumvent browser protections against programmatically closing a window, by "opening" the window programmatically first before closing it. I have seen references to this approach not working on some browser versions, but I don't know how that affects the range of versions we support.

The e2e tests here are passing, but the test for this close button might not be sufficient. Right now that test is configured to ensure the length of history on the phishing warning page is exactly 1 so that the browser considers it as being opened programmatically. The reason this test didn't catch the bug in the extension is that today the extension redirects to this page, resulting in a history length of 2. We should try to ensure the test accurately captures this scenario, so that it can protect against future regressions.

So I have 2 suggestions overall: consider browser support, and ensure the test is updated to catch this problem.

2023-03-23 12:48 UTC, danjm commented
with the change here, the tab is now left open, right? https://github.com/MetaMask/phishing-warning/pull/84/commits/fca89f3c061d3e0477e6f9164b33517f42d73699

2023-03-30 04:00 UTC, Gudahtt commented on tests/defaults.spec.ts
> +  // the redirection to MM extension will be tested in MM Extension e2e test
We can check in this test that the extension has at least been sent the correct message. See here for an example of how to do this: https://github.com/MetaMask/phishing-warning/blob/cb973a59e56108c754eb6f8fe88ef2c8e9b408c8/tests/bypass.spec.ts#L23

2023-03-30 11:50 UTC, danjm requested changes
Looks good. Just Mark's test suggestion to address

2023-03-30 13:07 UTC, DDDDDanica commented on tests/defaults.spec.ts
> +  // the redirection to MM extension will be tested in MM Extension e2e test
Thank you Mark, this is very helpful, and very easy to use ~

2023-03-30 13:22 UTC, danjm approved these changes
LGTM

2023-03-30 13:27 UTC, Gudahtt approved these changes
LGTM!

2023-03-30 17:26 UTC, merged